spring:
  application:
    name: Edu-Tracking-System
    
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
   # show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# APPLICATION CONFIGURATION
super_admin:
  email: ${SUPER-ADMIN_EMAIL}