spring:
  application:
    name: Edu-Tracking-System
    
  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# APPLICATION CONFIGURATION
super_admin:
  email: ${super-admin.email}